added HomePage, CarinaWebTest classes and components package
yana-glt/carina-demo pull request #1
Opened 2023-03-10 12:36 UTC by yana-glt

2023-03-15 11:52 UTC, vboltrukanis requested changes

2023-03-15 11:52 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/components/NavigationElementItem.java
> +    private ExtendedWebElement web;
```suggestion
public class NavigationElementItem extends AbstractUIObject {

    @FindBy(xpath = "//label[contains(text(),'Automation')]")
    private ExtendedWebElement automation;
    
    @FindBy(xpath = "//a[contains(text(),'Web')]")
    private ExtendedWebElement web;
```

2023-03-15 11:52 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/components/NavigationElementItem.java
> +    public ExtendedWebElement getAutomation() {
Try to not return webElements. Work with elements inside of pages / components. And from outside use only methods.

2023-03-15 11:52 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/components/SearchItem.java
> +    @FindBy(xpath="//header//input[@class='md-search__input']")
`//header//input` will be enough, do not overcomplicate it

2023-03-15 11:52 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/components/Url.java
> +public enum Url {
Maybe more descriptive name

2023-03-15 11:52 UTC, vboltrukanis commented on src/test/java/com/qaprosoft/carina/demo/CarinaWebTest.java
> +        Assert.assertTrue(homePage.getSearchItem().getSearchLogo().isElementPresent(),
you can use softAsserts here: https://www.seleniumeasy.com/testng-tutorials/soft-asserts-in-testng-example

2023-03-15 12:45 UTC, yana-glt commented on src/test/java/com/qaprosoft/carina/demo/CarinaWebTest.java
> +        Assert.assertTrue(homePage.getSearchItem().getSearchLogo().isElementPresent(),
I try to avoid using it here as Andrew said in a lecture that he strongly discourages using it as he has seen some examples and is not happy with how it works. But thanks for the info.

2023-03-15 12:57 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/components/NavigationElementItem.java
> +    private ExtendedWebElement web;
ok

2023-03-15 13:00 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/components/Url.java
> +public enum Url {
ok

2023-03-15 13:07 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/components/SearchItem.java
> +    @FindBy(xpath="//header//input[@class='md-search__input']")
yes, I agree, but I thought it makes sense to write something more specific, so that in case something is added to this element, for example, in subsequent tests, it could be more guaranteed to identify it. But if it's overkill - ok.

2023-03-16 15:32 UTC, vboltrukanis requested changes

2023-03-16 15:32 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/components/NavigationUrl.java
> +public enum NavigationUrl {
Why do you have enum in components folder?

2023-03-16 15:32 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/components/NavigationElementItem.java
> +    public void clickOnAutomation(){
`expandAutomationSection`

2023-03-16 15:32 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/components/SearchItem.java
> +    @FindBy(xpath = "//header//label[@class='md-search__icon md-icon']")
in components you can use relative xpath, which starts from `.//abc` , which will apply locator of component to this locators: `//header//div[@class='md-search']//abc`

2023-03-16 15:32 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/components/SearchItem.java
> +        searchPlaceholder = searchInput.getAttribute("ariaLabel");
```suggestion
    return searchInput.getAttribute("ariaLabel");
```

2023-03-16 15:32 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public boolean isSearchItemPresent() {
it should be like this: `return searchItem.isUIObjectPresent();`

2023-03-16 15:32 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +                    LOGGER.error("Search input component isn't present on header");
no need for logger here. We might want to validate that this element is not present on screen, so we don't expect to see errors in logs.

2023-03-16 15:32 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +        return cssValuePosition;
```suggestion
        return header.getElement().getCssValue("position");
```

2023-03-16 15:32 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +        System.out.println(elements.size());
clean code

2023-03-16 15:32 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public String getOverviewNavigationElementText() {
Is it a proper name. As i understand it returnes a text of active menu, so why do you have an overview section mentioned here.

2023-03-16 15:32 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public boolean isWebPresentOnPage() {
isWebSectionPresentOnPage

2023-03-16 15:32 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public List<String> getAttributeHrefFromNavigationList(ExtendedWebElement element) {
do not use methods which accept ExtendedWebElement as a parameter, think how to refactor this.

2023-03-16 15:32 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public boolean isAttributeHrefCorrect(List<String> listOfNameAndHref) {
You are passing a list, to get only one value from it and validate it?)))

2023-03-17 10:54 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/components/NavigationUrl.java
> +public enum NavigationUrl {
Simply because I needed to place it somewhere. It seemed to me that in components are more logical than in pages package. But I can also create a separate package. I just tried to stick to the package structure suggested in the example.

2023-03-17 11:18 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/components/SearchItem.java
> +    @FindBy(xpath = "//header//label[@class='md-search__icon md-icon']")
yes, that's much better. Thank you

2023-03-17 11:31 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/components/NavigationUrl.java
> +public enum NavigationUrl {
Create a separate package plz. You can do it inside of components if you want to, or on the same level as components/pages

2023-03-17 11:38 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/components/SearchItem.java
> +        searchPlaceholder = searchInput.getAttribute("ariaLabel");
ok

2023-03-17 11:38 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public boolean isSearchItemPresent() {
ok

2023-03-17 11:39 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +                    LOGGER.error("Search input component isn't present on header");
ok

2023-03-17 11:40 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +        return cssValuePosition;
ok

2023-03-17 11:43 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +        System.out.println(elements.size());
sorry

2023-03-17 11:59 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public String getOverviewNavigationElementText() {
so I tried to complete the task
Navigation element is visible
Steps:
go to carina docs
Validate:
Carina heading is first element of navigation menu
list of navigation link is present
current page link is highlighted

in this method using xpath "//li[@class='md-nav__item md-nav__item--active']" I find which item from the navigation menu is highlighted (it will be "md-nav__item--active"). In the getOverviewLabelText() method, I determine what is currently in the title on the page. I take the text from these 2 elements and compare, thereby confirming that what is highlighted in the navigation menu is reflected on the page at this moment.
maybe this is not the best way to check the highlighted element...)) But I don't know a more correct and rational way yet.

2023-03-17 11:59 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public boolean isWebPresentOnPage() {
ok

2023-03-17 12:11 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public boolean isAttributeHrefCorrect(List<String> listOfNameAndHref) {
not really. only a list of 2 strings = name and href gets into this method, and they are checked in this method for equality (by name from enum, I take the corresponding href for the page and compare it with the one I get from the page code).
then this method is called in the CarinaWebTest class only once for each element from the navigation menu to compare

 @Test
    @MethodOwner(owner = "ygalitsyna")
    @TestPriority(Priority.P3)
    public void testNavigationWorksProperly() {
        HomePage homePage = new HomePage(getDriver());
        homePage.open();
        for (ExtendedWebElement el : homePage.getNavigationList()) {
            Assert.assertTrue(homePage.isAttributeHrefCorrect(homePage.getAttributeHrefFromNavigationList(el)),
                        "The element contains an invalid page link");
        }
    }

2023-03-17 12:38 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public List<String> getAttributeHrefFromNavigationList(ExtendedWebElement element) {
To be honest, I don't quite understand how this can be done. if you remember, you recommended:

[vboltrukanis](https://github.com/vboltrukanis) [2 days ago](https://github.com/yana-glt/carina-demo/pull/1#discussion_r1136929167)
Try to not return webElements. Work with elements inside of pages / components. And from outside use only methods.

therefore, I tried to implement as much as possible all the logic for checking the web element inside the HomePage class. To check all links to 21 elements inside the navigation menu, I somehow need to pass either a list of these elements, or each element to a method that will iterate over them.

2023-03-17 13:43 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/components/NavigationUrl.java
> +public enum NavigationUrl {
I did

2023-03-17 14:36 UTC, vboltrukanis commented on src/test/java/com/qaprosoft/carina/demo/CarinaWebTest.java
> +        Assert.assertTrue(homePage.getSearchItem().getSearchLogo().isElementPresent(),
Try it at least, so you will not be suprised if you see it in a project.

2023-03-17 14:36 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/components/SearchItem.java
> +    @FindBy(xpath="//header//input[@class='md-search__input']")
No, more specific means that it is higher chances that it will break at some point and fail your regression. Try to make it as stable as possible.

2023-03-17 14:42 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/components/SearchItem.java
> +    @FindBy(xpath="//header//input[@class='md-search__input']")
I think I already fixed it. In the last pull request, it already looked like this
 
  @FindBy(xpath = ".//form//label")
    private static ExtendedWebElement searchLogo;

    @FindBy(xpath = ".//input")
    private static ExtendedWebElement searchInput;

2023-03-17 14:43 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public String getOverviewNavigationElementText() {
```
@FIndBy(xpath = "//li[contains(@class, 'md-nav__item') and .//a[text()='%s']]")
private ExtendedWebElement  navElement;

...

return navElement.format("Overview").getAttribute("class").contains("md-nav__item--active");
```

2023-03-17 14:44 UTC, yana-glt commented on src/test/java/com/qaprosoft/carina/demo/CarinaWebTest.java
> +        Assert.assertTrue(homePage.getSearchItem().getSearchLogo().isElementPresent(),
ok

2023-03-17 17:00 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public boolean isAttributeHrefCorrect(List<String> listOfNameAndHref) {
List of elements means that this should be a list of similar objects (strings). In this case, pass two parameters (String name, String href) to make it more readable

2023-03-17 21:33 UTC, yana-glt commented on src/test/java/com/qaprosoft/carina/demo/CarinaWebTest.java
> +        Assert.assertTrue(homePage.getSearchItem().getSearchLogo().isElementPresent(),
done

2023-03-17 22:00 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public boolean isAttributeHrefCorrect(List<String> listOfNameAndHref) {
done

2023-03-17 22:37 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/ui/pages/HomePage.java
> +    public String getOverviewNavigationElementText() {
Cool. Thank you. That's better.

2023-04-03 13:25 UTC, merged