Api
yana-glt/carina-demo pull request #2
Opened 2023-03-13 19:13 UTC by yana-glt

2023-03-15 11:45 UTC, vboltrukanis requested changes

2023-03-15 11:45 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/api/GetCheckDefaultPaginationMethod.java
> +        addParameter("client_id", "oZqNRI9G64U6XQonRp5aZduKHySCnEB55zH_Xuko-ZI");
Do not expose secrets!

2023-03-15 11:45 UTC, vboltrukanis commented on src/main/java/com/qaprosoft/carina/demo/api/GetCheckDefaultPaginationMethod.java
> +@Endpoint(url = "${base_url}/collections/9242294/photos", methodType = HttpMethodType.GET)
collectionId can be a variable replacd in method.

2023-03-15 11:45 UTC, vboltrukanis commented on src/test/java/com/qaprosoft/carina/demo/APICarinaTest.java
> +    @MethodOwner(owner = "yana-glt")
Company standard will be: `ygalitsyna`

2023-03-15 11:45 UTC, vboltrukanis commented on src/test/java/com/qaprosoft/carina/demo/APICarinaTest.java
> +        Assert.assertEquals(total,totalPages);
```suggestion
        Assert.assertEquals(total, totalPages);
```

2023-03-15 11:45 UTC, vboltrukanis commented on src/test/java/com/qaprosoft/carina/demo/APICarinaTest.java
> +        Assert.assertEquals(total,totalPages);
Total is a total number of results, totalPages is number of pages: totalPages = total / resultsPerPage

2023-03-15 11:51 UTC, yana-glt commented on src/test/java/com/qaprosoft/carina/demo/APICarinaTest.java
> +    @MethodOwner(owner = "yana-glt")
ok

2023-03-15 11:55 UTC, yana-glt commented on src/test/java/com/qaprosoft/carina/demo/APICarinaTest.java
> +        Assert.assertEquals(total,totalPages);
yes, but in this test, I check that the api responds correctly to the request of one element on one page. 

public GetPhotosMethod() {
        addParameter("query", "krakow");
        addParameter("page", "1");
        addParameter("per_page", "1");
        
        Therefore, specifically here, the number of pages should be equal to the number of elements in the selection

2023-03-15 12:26 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/api/GetCheckDefaultPaginationMethod.java
> +        addParameter("client_id", "oZqNRI9G64U6XQonRp5aZduKHySCnEB55zH_Xuko-ZI");
fixed it

2023-03-15 12:34 UTC, yana-glt commented on src/main/java/com/qaprosoft/carina/demo/api/GetCheckDefaultPaginationMethod.java
> +@Endpoint(url = "${base_url}/collections/9242294/photos", methodType = HttpMethodType.GET)
I tried to overload this method (to add, in addition to the default implementation with the specified id, a method with a String parameter so that the id can be changed). But it doesn't work. Do you mean to make it a local variable inside the method instead of a direct url?

2023-03-16 15:34 UTC, vboltrukanis approved these changes

2023-04-03 13:24 UTC, merged